### ISSUE TITLE
Random Velocities

### ISSUE THREAD

**Issue by Lrolmar** [insilichem/ommprotocol#13]
Hello!

I would like to run replicas with your script, but starting from a restart point and **randomizing the initial velocities**. Is this already considered in your script or should I change something?

Thank you.

**Comment by jaimergp** [comment]
I am not sure this would work with the current code (otherwise, the changes should be easy), but you can try with `velocities: None` (`null` in Yaml speech), which would force reassignation from the Boltzmann distribution:

```yaml
# input
topology: sys.prmtop
velocities: null
checkpoint: simulation.state.xml
```
