### ISSUE TITLE
Box not detected in pdb file (Charmm)

### ISSUE THREAD

**Issue by Lrolmar** [insilichem/ommprotocol#16]
Hi there!

I have been trying to perform MD simulations with a .psf and .pdb file, but an error arises that the system is not under periodic boundary conditions. I checked and the water box is properly defined in the .pdb file (in the first line). How can I solve it?

**Comment by jaimergp** [comment]
Apparently the `CharmmPsfFile` handlers requires their `periodicBoxVectors` keyword to be set to the `has_box` checks are done upon system creation. This is now fixed in latest master and will be in the next patch release. Thanks for the report!

**Comment by jaimergp** [comment]
[`v0.1.13` is online at `-c insilichem`](https://anaconda.org/InsiliChem/ommprotocol/files?version=0.1.13). It can be installed in an existing environment with:

```
conda install -c conda-forge -c omnia -c insilichem ommprotocol=0.1.13
```

Take into account that for this fix to be applied, box vectors must be specified explicitly (even using the same file if needed):

```yaml
topology: helix_wb.psf
positions: helix_wb.pdb
box: helix_wb.pdb  # <<<--- this line is needed
forcefield:
  - top_all36_prot.rtf
  - toppar/toppar_water_ions.str
  - par_all36m_prot.prm

```
